apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-duke
  labels:
    app.kubernetes.io/name: helloworld-duke
    app.kubernetes.io/instance: helloworld-duke
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: helloworld-duke
      app.kubernetes.io/instance: helloworld-duke
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helloworld-duke
        app.kubernetes.io/instance: helloworld-duke
    spec:
      containers:
        - name: helloworld-duke
          image: asia.gcr.io/poc-innovation-iot/helloworld-duke
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          resources: 
            limits: 
              cpu: 64m
              memory: 32Mi
            requests: 
              cpu: 32m
              memory: 6