apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
namespace: ice-training
images:
- name: asia.gcr.io/poc-innovation-iot/helloworld-ice
  newTag: 0533b581
