apiVersion: v1
kind: Service
metadata:
  name: helloworld-duke
  labels:
    app.kubernetes.io/name: helloworld-duke
    app.kubernetes.io/instance: helloworld-duke
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: helloworld-duke
    app.kubernetes.io/instance: helloworld-duke
